In [1]:
import sklearn

In [18]:
from scipy.sparse.csgraph import shortest_path
from scipy.sparse import csr_matrix
import numpy as np

In [19]:
graph = [
[0, 1, 2, 0],
[0, 0, 0, 1],
[2, 0, 0, 3],
[0, 0, 0, 0]
]
graph = np.array(graph)
#graph = csr_matrix(graph)
#print(graph)

In [20]:
graph

array([[0, 1, 2, 0],
       [0, 0, 0, 1],
       [2, 0, 0, 3],
       [0, 0, 0, 0]])

In [21]:
dist_matrix, predecessors = shortest_path(csgraph=graph, directed=False, indices=0, return_predecessors=True)

In [22]:
dist_matrix


array([0., 1., 2., 2.])

In [63]:
edge = dict()
edge[0] = [1,2]
edge[1] = [0,3]
edge[2] = [0,3]
edge[3] = [1,2]

def to_adjacency_matrix(edge):
    N=len(edge.keys())
    edge_matrix = np.zeros((N,N))
    for row in range(N):
        cols = edge[row]
        if cols:
            edge_matrix[row,cols] = 1 
    indx = np.diag_indices(N)
    edge_matrix[indx] = 0
    return edge_matrix

In [64]:
graph = to_adjacency_matrix(edge)

In [66]:
dist_matrix, predecessors = shortest_path(csgraph=graph, directed=False, indices=0, return_predecessors=True)

In [67]:
dist_matrix

array([0., 1., 1., 2.])

In [70]:
predecessors

array([-9999,     0,     0,     1])

In [74]:
def get_shortest_path_nodes(start, end, previous_nodes):
    visit_nodes = []
    curr = end
    while previous_nodes[curr] != start:
        visit_nodes.insert(0,previous_nodes[curr])
        curr = previous_nodes[curr] 
    return [start] + visit_nodes + [end]
    

In [75]:
get_shortest_path_nodes(0, 3, predecessors)

[0, 1, 3]