In [3]:
#References:
#https://www.geeksforgeeks.org/python-maximum-minimum-elements-position-list/
#https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.sort.html
# https://stackoverflow.com/questions/31999317/finding-second-smallest-element-in-array 
# http://codinghelmet.com/exercises/two-smallest
    

In [4]:
import numpy as np
def eu_dist(p,q):
    return np.sqrt(np.sum((p-q)**2))

p=np.array([1,2,5])
q=np.array([1,6,5])
eu_dist(p,q)

4.0

In [5]:
np.array([[1,3,4],[5,3,1]]).shape


(2, 3)

In [6]:
import numpy as np

distances= min(np.array([1,4,30,14,7,8]))
print(distances)
#id(distances) #Memory location(pointer)
 


1


In [7]:
def kMinimumDist(distances, kNearest): 
    
    distances.sort(reverse=False)  
    for eachDist in range(kNearest): 
        print (distances[eachDist],end =" ")         # end =" " prints array horizonally
  

distances = [1, 23, 32, 9, 30, 22, 50] 
kNearest = 3 
kMinimumDist(distances, kNearest) 

  

1 9 22 

In [8]:
# train_data(Xi,Yi)
# Xi=features
# Yi=Corresponding labels

In [9]:
import math
import numpy as np
dog_data=[2,3,4,5]
dog_labels=[0,0,0,0]
cat_data=[6,7,8,9]
cat_labels=[1,1,1,1]
k=1
train_data=np.array([2,3,8,9])
train_labels=np.array([0,0,1,1])
test_data=np.array([7])
difference=np.array(test_data-train_data)**2
minimum_distance=min(np.sqrt(difference))
print(difference)
print("minimum distance=",minimum_distance)
index_min = np.argmin(difference)
print("Position of minimum distance =",index_min)

[25 16  1  4]
minimum distance= 1.0
Position of minimum distance = 2


In [10]:
mapper=dict(zip(train_data, train_labels))
mapper

{2: 0, 3: 0, 8: 1, 9: 1}

In [11]:
import numpy as np
test_array = np.array([1,4,2,4,-1,8])
for i,element in enumerate(test_array):
    # write code to find (i) which contains min value
    min(test_array)
    print (i,element)
#found_min_at_array = 4 is output for above statement
#print (test_array[found_min_at_index] == -1)

0 1
1 4
2 2
3 4
4 -1
5 8


In [15]:
import numpy as np
test_array = np.array([1,4,2,4,-1,8])

for i,element in enumerate(test_array):
    
    print (test_array[minimum_element])


NameError: name 'minimum_element' is not defined

In [16]:
test_array =[1,4,2,4,-1,8]
test_array.index(min(test_array))          #https://www.geeksforgeeks.org/python-maximum-minimum-elements-position-list/

4

In [17]:
# Tuesday ,    19.02.2019

In [18]:
import math
import numpy as np
dog_data=[2,3,4,5,15,19,20]
dog_labels=[0,0,0,0,0,0,0]
cat_data=[6,7,8,9,13,11,16]
cat_labels=[1,1,1,1,1,1,1]
k=1
train_data=np.array([2,3,8,9,19,11,20])
train_labels=np.array([0,0,1,1,0,1,0])
test_data=np.array([7])
difference=np.array(test_data-train_data)**2
minimum_distance=min(np.sqrt(difference))
sorted_array=np.sort(difference)                #https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.sort.html
print(difference)
print(sorted_array)
print("minimum distance=",minimum_distance)
index_min = np.argmin(difference)
print("Position of minimum distance =",index_min)

[ 25  16   1   4 144  16 169]
[  1   4  16  16  25 144 169]
minimum distance= 1.0
Position of minimum distance = 2


In [19]:
 def kMinimumDist(distances, kNearest): 
    
    distances.sort(reverse=False)  
    for eachDist in range(kNearest): 
        print (distances[eachDist],end =" ")  
   
distances = [25,16,1,4,144,16,169] 
kNearest = 3 
kMinimumDist(distances, kNearest) 
first_min=distances.index(min(distances))
print("\n Position of First minimum distance =",first_min)
print("Position of Second minimum distance =",first_min+1)
print("Position of Third minimum distance =",first_min+2)


    

1 4 16 
 Position of First minimum distance = 0
Position of Second minimum distance = 1
Position of Third minimum distance = 2


In [20]:
import numpy as np
temp=np.array([1,5,3,8,10,100,25])

indexes=[3,0,5]

temp[indexes]

array([  8,   1, 100])

In [21]:
# Wednesday 20.02.2019

In [22]:
# import numpy as np
# temp=np.array([25,16,1,4,144,16,169])
# k=4
# labels[np.argsort(temp)[0:k]]



In [23]:
import numpy as np
numbers=np.array([25,16,1,4,144,-1])
min_number=numbers[0]
for element in range(len(numbers)):
    if numbers[element]<min_number:
        min_number=numbers[element]
print("minimum number in an array =",min_number)          

minimum number in an array = -1


In [24]:
#Thursday, 21.02.2019

In [25]:
import numpy as np
numbers=np.array([25,16,1,4,144,169])
first_min=numbers[0]
second_min=numbers[1]
if second_min<first_min:
    first_min=numbers[1]
    second_min=numbers[0]
for i in range(len(numbers)):
    if numbers[i]<first_min:
        second_min=first_min
        first_min=numbers[i]
    elif numbers[i]<second_min:
        second_min=numbers[i]
print("First minimum number= ",first_min)    
print("Second minimum number= ",second_min)
        

 

First minimum number=  1
Second minimum number=  4


In [26]:
 x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [27]:
import math
import numpy as np
dog_data=[2,3,4,5,15,19,20]
dog_labels=[0,0,0,0,0,0,0]
cat_data=[6,7,8,9,13,11,16]
cat_labels=[1,1,1,1,1,1,1]

# Convert below lines into function
k=3
train_data=np.array([2,3,8,9,19,11,20])
train_labels=np.array([0,0,1,1,0,1,0])
test_data=np.array([7])
difference=np.array(test_data-train_data)**2 # naming wrong
np.argsort(difference)               #https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.sort.html
#comment required
Labels=train_labels[np.argsort(difference)[0:k]] #naming wrong kNearest_labels
sorted_array=np.sort(difference) # wrong naming sorted_EuDist

print("Array of Euclidean Distances= ",difference)
print("Train Labels", train_labels)
print("Sorted =",sorted_array)
print("Corresponding Labels when k=3  ",Labels)

#Work required. Output is label for test point



Array of Euclidean Distances=  [ 25  16   1   4 144  16 169]
Train Labels [0 0 1 1 0 1 0]
Sorted = [  1   4  16  16  25 144 169]
Corresponding Labels when k=3   [1 1 0]


In [28]:
import numpy as np
train_data=np.array([2,3,8,9,19,11,20])
print(train_data.shape)
train_data=train_data[:,np.newaxis]

print (train_data)
print(train_data.shape)
test_data=np.array([6])
(test_data[:,np.newaxis] - train_data)**2

(7,)
[[ 2]
 [ 3]
 [ 8]
 [ 9]
 [19]
 [11]
 [20]]
(7, 1)


array([[ 16],
       [  9],
       [  4],
       [  9],
       [169],
       [ 25],
       [196]], dtype=int32)

In [29]:
# Function definition is here
def printme( str ):
   "This prints a passed string into this function"
   print (str)
   return;

# Now you can call printme function
printme("I'm first call to user defined function!")
printme("Again second call to the same function")

I'm first call to user defined function!
Again second call to the same function


In [30]:
#27.02.2019

In [31]:
def additionOf2numbers(a,b):
    result=a+b
    print(result)

additionOf2numbers(30,50)

80


In [32]:
def additionOf2numbers(a,b):
    a=45
    b=5
    result=a+b
    print(result)

additionOf2numbers(30,5)
result= 30+5
print("Result Outside =",result)

50
Result Outside = 35


In [33]:
import numpy as np


def minimumNumbers(numbers):
    first_min=numbers[0]
    second_min=numbers[1]
    if second_min<first_min:
        first_min=numbers[1]
        second_min=numbers[0]
    for i in range(len(numbers)):
        if numbers[i]<first_min:
            second_min=first_min
            first_min=numbers[i]
        elif numbers[i]<second_min:
            second_min=numbers[i]
    print("First minimum number= ",first_min)    
    print("Second minimum number= ",second_min)

numbers=np.array([25,16,1,4,144,169])            
minimumNumbers(numbers)            







First minimum number=  1
Second minimum number=  4


In [44]:
import math
import numpy as np
import collections
from collections import Counter

dog_data=[2,3,4,5,15,19,20]
dog_labels=[0,0,0,0,0,0,0]
cat_data=[6,7,8,9,13,11,16]
cat_labels=[1,1,1,1,1,1,1]

# Convert below lines into function
k=3
train_data=np.array([2,3,8,9,19,11,20])
train_labels=np.array([0,0,1,1,0,1,0])
test_data=np.array([7])


def KNN_algo(test_data,k):
    # See python coding guidelines and makes notes for below (Google coding guidelines)
    
    # First set of notations (dtype basis)
        
        #if scalar ?   See python coding guidelines. naming of variables - vector, scalar and multidimentional ? look for notations
        #if vector ?    
        #if multidimentinal ?
        #constant ?
        
        #dict 
        #tuple
        #list
        
    # function naming (notations) 
    
    # scope based notations
        #local scope ?
        #global scope ?
    
    EuclideanDist=np.sqrt(np.array(test_data-train_data)**2) # E small letter
                #https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.sort.html
#comment required
    kNearest_labels=train_labels[np.argsort(EuclideanDist)[0:k]] 
    sorted_EuDist=np.sort(EuclideanDist)
    counted_labels= collections.Counter(kNearest_labels)  #https://pymotw.com/2/collections/counter.html
    

    print("Array of Euclidean Distances= ",EuclideanDist)
    print("Train Labels", train_labels)
    print("Sorted =",sorted_EuDist)
    print("Corresponding Labels when k=3  ",kNearest_labels)
    print("Counted labels=",counted_labels)


KNN_algo(test_data,k)

#Work required. Output is label for test point


Array of Euclidean Distances=  [ 25  16   1   4 144  16 169]
Train Labels [0 0 1 1 0 1 0]
Sorted = [  1   4  16  16  25 144 169]
Corresponding Labels when k=3   [1 1 0]
Counted labels= Counter({1: 2, 0: 1})


In [ ]:
#  https://stackoverflow.com/questions/48035298/is-there-a-naming-convention-to-distinguish-scalar-and-vectors

# https://www.python.org/dev/peps/pep-0008/#global-variable-names

# module_name, package_name, ClassName, method_name, ExceptionName,
# function_name, GLOBAL_CONSTANT_NAME, global_var_name, instance_var_name,
# function_parameter_name, local_var_name

# Constants:
# Constants are usually defined on a module level and written in all capital letters with underscores separating words. 
# Examples include MAX_OVERFLOW and TOTAL.



# Naming Conventions:
    
# Module names should be lowercase with underscores instead of spaces. ...
# Variable names and function/method names should also be lowercase with underscores to separate words.
# Class names should be CamelCase (uppercase letter to start with, words run together, each starting with an uppercase letter)


# Function and Variable Names:
    
# Function names should be lowercase, with words separated by underscores as necessary to improve readability.

# Variable names follow the same convention as function names.

# mixedCase is allowed only in contexts where that's already the prevailing style (e.g. threading.py), to retain backwards compatibility.

In [9]:
import math
import numpy as np
import collections
from collections import Counter

dog_data=[2,3,4,5,15,19,20]
dog_labels=[0,0,0,0,0,0,0]
cat_data=[6,7,8,9,13,11,16]
cat_labels=[1,1,1,1,1,1,1]


K=3
train_data=np.array([2,3,8,9,19,11,20])
train_labels=np.array([0,0,1,1,0,1,0])
test_data=np.array([7])


def knn_algo(test_data,K):
    
    euclidean_dist=np.sqrt(np.array(test_data-train_data)**2) 
     
    knearest_labels=train_labels[np.argsort(euclidean_dist)[0:K]] 
    
    sorted_eu_dist=np.sort(euclidean_dist)
    counted_labels= collections.Counter(knearest_labels)  #https://pymotw.com/2/collections/counter.html
    result=max(counted_labels, key=counted_labels.get)

    print("Array of Euclidean Distances= ",euclidean_dist)
    print("Train Labels", train_labels)
    print("Sorted =",sorted_eu_dist)
    print("Corresponding Labels when k=3  ",knearest_labels)
    print("Counted labels=",counted_labels)
    print(result)
    
    if result==0:
        print("predicted result = {}".format("dog"))
    else:
        print("predicted result = {}".format("cat"))

knn_algo(test_data,K)



#Work required. Output is label for test point


Array of Euclidean Distances=  [ 5.  4.  1.  2. 12.  4. 13.]
Train Labels [0 0 1 1 0 1 0]
Sorted = [ 1.  2.  4.  4.  5. 12. 13.]
Corresponding Labels when k=3   [1 1 0]
Counted labels= Counter({1: 2, 0: 1})
1
predicted result = cat


In [10]:
import math
import numpy as np
import collections
from collections import Counter

dog_data=[2,3,4,5,15,19,20]
dog_labels=[0,0,0,0,0,0,0]
cat_data=[6,7,8,9,13,11,16]
cat_labels=[1,1,1,1,1,1,1]


K=3
train_data=np.array([2,3,8,9,19,11,20])
train_labels=np.array([0,0,1,1,0,1,0])
test_data=np.array([7])

"""  NEXT TASKS
    1. Make it work for any dimensionality of test data, train data and input data.
    2. 
"""

def knn_algo(test_data,K):
    # euclidean distances from test data point to all train data points
    euclidean_dist = np.sqrt( np.array( test_data-train_data )**2 ) 
     
    knearest_labels = train_labels[ np.argsort(euclidean_dist)[0:K] ] # knearest_train_labels would be better
    
    sorted_eu_dist = np.sort(euclidean_dist) # distance has to be plural if list
    counted_labels = collections.Counter(knearest_labels)  #https://pymotw.com/2/collections/counter.html
    result = max(counted_labels, key=counted_labels.get)

#     print("Array of Euclidean Distances= ",euclidean_dist)
#     print("Train Labels", train_labels)
#     print("Sorted =",sorted_eu_dist)
#     print("Corresponding Labels when k=3  ",knearest_labels)
#     print("Counted labels=",counted_labels)
#     print(result)
    
    if result==0:
        print("predicted result = {}".format("dog"))
    else:
        print("predicted result = {}".format("cat"))

knn_algo(test_data,K)





predicted result = cat


In [1]:
a = [[1, 2, 3, 4], [5, 6], [7, 8, 9]]
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=' ')
    print()

1 2 3 4 
5 6 
7 8 9 


In [10]:
a=[[1,2,3], [5,6,6], [7,8,9]]
for i in range(len(a[i])):
    print(a[i])

[1, 2, 3]
[5, 6, 6]
[7, 8, 9]


In [40]:
import math
import numpy as np
import collections
from collections import Counter

dog_data=[[2,3,4,5,15,19,20],[1,2,4,5,7,86,9]]
dog_labels=[0,0,0,0,0,0,0]
cat_data=[[6,7,8,9,13,11,16],[5,8,74,16,3,48,13]]
cat_labels=[1,1,1,1,1,1,1]


K=3
train_data=np.array([(2,3,8,9,19,11,20),(2,1,26,33,35,6,10)])
train_labels=np.array([0,0,1,1,0,1,0])
test_data=np.array([14,2,44,88,55,32,11])



def knn_algo(test_data,K):
    # euclidean distances from test data point to all train data points
    euclidean_dist = np.sqrt( np.array( test_data-train_data )**2 ) 
     
    knearest_labels = train_labels[ np.argsort(euclidean_dist)[0:K] ] # knearest_train_labels would be better
    
    sorted_eu_dist = np.sort(euclidean_dist) # distance has to be plural if list
    counted_labels = collections.Counter(knearest_labels)  #https://pymotw.com/2/collections/counter.html
    result = max(counted_labels, key=counted_labels.get)

#     print("Array of Euclidean Distances= ",euclidean_dist)
#     print("Train Labels", train_labels)
#     print("Sorted =",sorted_eu_dist)
#     print("Corresponding Labels when k=3  ",knearest_labels)
#     print("Counted labels=",counted_labels)
#     print(result)
    
    if result==0:
        print("predicted result = {}".format("dog"))
    else:
        print("predicted result = {}".format("cat"))

knn_algo(test_data,K)


TypeError: unhashable type: 'numpy.ndarray'

In [41]:
 euclidean_dist = np.sqrt( np.array( test_data-train_data )**2 )


In [44]:
print(euclidean_dist)
print(test_data)
print(train_data)

[[12.  1. 36. 79. 36. 21.  9.]
 [12.  1. 18. 55. 20. 26.  1.]]
[14  2 44 88 55 32 11]
[[ 2  3  8  9 19 11 20]
 [ 2  1 26 33 35  6 10]]


In [31]:
a = np.array([(1, 2, 3),(4,5,6)])
b = np.array([2, 2, 2])

(2, 3)

In [33]:
b.shape


(3,)

In [34]:
a*b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [37]:
g= np.array([(2,3,8,9,19,11,20),(2,1,26,33,35,6,10)])
h= np.array([14,2,44,88,55,32,11])

In [38]:
g*h

array([[  28,    6,  352,  792, 1045,  352,  220],
       [  28,    2, 1144, 2904, 1925,  192,  110]])

In [ ]:
"""
   Comments from Praveen:
   
   1) find the details about collections data structure. This is last point.
   2) document the how and when to use collections ?
   3) What is meaning of hashable data structure ?
   4) Difference between dictionary, list and tuples.
   5) How is collections related to dictionary data structure.
   6) Document all the answers in github doc folder.
   
   Fyi:  While explanation in doc also give examples. Execute them in jupyter. Documentation must be in Jupyter. Heading of Jupyter
   is Data structures in Python.
   
   ---> Pointers to start answering above questions:
   
   First look at python basic data structure --> Dictionary, tuple, lists.
   
   
   

"""

In [1]:
dictionary - unordered.
tuple - immutable, less space, less time.
lists - mutable, ordered . More space, more time. Can include any data types.

SyntaxError: invalid syntax (<ipython-input-1-fb795f5a9e76>, line 1)

In [1]:
"""
List is a ordered data type. Ordered means elements are arranged in the consecutive elements.

"""
ListData = [1, 2, 3, 4]

ListData[0]
ListData[1]

"""
Tuple is non mutable datatype
"""

TupleData = (1,2,3)

TupleData[0] = 1





TypeError: 'tuple' object does not support item assignment